/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Index } from "./Index";
export * as factories from "./factories";
export { Index__factory } from "./factories/Index__factory";
